name: Deploy Hugo Site

on:
  push:
    branches: [ "hugo" ]
    paths-ignore:
      - 'README.md'
      - '.gitattributes'
      - '.gitignore'
      - '.vscode/**'
      - 'LICENSE'
      - '.idea/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: jimdtech/jimdiroffii-dot-com:latest

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd /opt/docker/jimdiroffii-dot-com
            
            # Pull the new image we just pushed
            docker compose pull
            
            # Recreate the container with the new image
            docker compose up -d
            
            # Clean up old images to save disk space
            docker system prune -f